### ISSUE TITLE
Exibir simulação de frete na página de produto

### ISSUE THREAD

**Issue by claudiosanches** [claudiosmweb/woocommerce-correios#2]
Falta ainda criar uma opção para exibir um simulador de frete na página do produto.

Aproveitar e criar também um shortcode para isso.

**Comment by burburim** [comment]
Boa noite Claudio, Já há um shortcode pra isso? Estou querendo colocar esse simulador em um popup modal em meu site.

**Comment by claudiosmweb** [comment]
@burburim não e não vai ter.

**Comment by burburim** [comment]
obrigado. e parabens pelo plugin!

**Comment by mmicas** [comment]
Não consigo add na página do produto, a simulação do frete. Qual o código que posso inserir para aparecer o plugin?
