### ISSUE TITLE
PAC Gratuito

### ISSUE THREAD

**Issue by filipe-cs** [claudiosmweb/woocommerce-correios#25]
Olá, Cláudio.
Antes de mais nada, meus parabéns pela iniciativa e pelo excelente trabalho que vc faz.

Seria possível usar o PAC como o meu frete gratuito?

Obrigado.

**Comment by claudiosmweb** [comment]
Sim é possível só usar o filtro `woocommerce_correios_shipping_methods`.

**Comment by filipe-cs** [comment]
Cláudio, poderia me dar um help?
add_filter('woocommerce_correios_shipping_methods', 'pac_gratuito');
function pac_gratuito($rates, $package){
    $rates['service_sedex']['cost'] = 0;
	
	return $rates;
}

**Comment by claudiosmweb** [comment]
Aqui não é bem o lugar para isso, este fórum é usado para novas features ou bugs com o plugin.
Se eu tiver tempo eu escrevo um post sobre isso hoje e publico no grupo.

**Comment by filipe-cs** [comment]
Blz =]

**Comment by claudiosmweb** [comment]
http://claudiosmweb.com/woocommerce/woocommerce-deixar-o-metodo-de-entrega-pac-dos-correios-gratuito/

**Comment by filipe-cs** [comment]
Sem palavras... muuuito obrigado!

2015-01-20 0:11 GMT-02:00 Claudio Sanches <notifications@github.com>:
