### ISSUE TITLE
Failed to connect to ws.correios.com.br port 80 ("Nenhuma opção de entrega foi encontrada para..."

### ISSUE THREAD

**Issue by rbettoni** [claudiosmweb/woocommerce-correios#254]
Olá, pessoal.

Estou enfrentando um problema que vejo ser recorrente - ao fazer o checkout, o sistema mostra a mensagem "Nenhuma Opção De Entrega Foi Encontrada Para…".
Verifiquei os logs e percebi que o plugin não está conectando com os correios, mostrando esta mensagem:

09-18-2023 @ 14:21:01 - WP_Error: cURL error 7: Failed to connect to ws.correios.com.br port 80 after 168 ms: Couldn't connect to server

alguma ideia do que pode ser feito?
Muito obrigado

**Comment by aliceyorkes** [comment]
Está acontecendo exatamente o mesmo erro com um dos meus sites. Entrei em contato com o suporte do woo comerce e eles não me deram uma solução, só falaram pra eu entrar em contato com o desenvolvedor (que seria eu) ou contratar o serviço deles.

**Comment by ricardobrg** [comment]
Os Correios mudaram a API ontem desativando o webservice. Precisa mudar para a nova API.https://github.com/claudiosanches/woocommerce-correios#configura%C3%A7%C3%A3o-do-plugin

**Comment by aliceyorkes** [comment]
Desse modo então meu site só vai voltar ao normal se eu fechar um contrato com os correios?

**Comment by rbettoni** [comment]
> Os Correios mudaram a API ontem desativando o webservice. Precisa mudar para a nova API.https://github.com/claudiosanches/woocommerce-correios#configura%C3%A7%C3%A3o-do-plugin

Obrigado, Ricardo! Estou testando aqui -- ainda não consegui, o sistema não atualiza a lista de serviços -- mesmo com todas as informações corretas (token e usuário), mostra a mensagem "Não foi possível recuperar a lista de serviços!".

**Comment by felipersilva-agro** [comment]
Olá @rbettoni estou com o mesmo problema em um cliente, você conseguiu avançar nessa questão ?

**Comment by tgoribas** [comment]
> Olá @rbettoni estou com o mesmo problema em um cliente, você conseguiu avançar nessa questão ?

Mesmo problema aqui, alguma solução ?

**Comment by palimpsestus** [comment]
@felipersilva-agro @tgoribas consegui seguindo as orientações daqui -- gerei token nos Correios, inseri e deu tudo certo. O contrato e o cartão de postagem precisam estar ativos nos correios - se houver qualquer problema no contrato, o token não funciona. eu havia excedido meu limite de postagem, por isso não consegui antes.

No entanto, o token que foi gerado ontem já não validou hoje, precisei gerar outro. Não entendi porque venceu, pois supostamente a validade é indeterminada.

Também não sei se há como gerar o token ou acessar a API sem ter contrato com os correios.

Vocês verificaram o log de atividades pra ver possíveis problemas?

**Comment by felipersilva-agro** [comment]
Olha os correios me disseram agora que esta tudo ok com o cadasttro do cliente.

No log do woocommerce aparece isso? 
09-19-2023 @ 07:33:35 - WP_Error: cURL error 7: Failed to connect to ws.correios.com.br port 80: Connection refused

Estou relendo as paginas de ajuda com calma para ver se deixei passar algo

**Comment by tgoribas** [comment]
@palimpsestus @felipersilva-agro na configuração me parece que está tudo ok, o Nome de usuário, Código de Acesso e Cartão de Postagem.
Será que é algum problema no contrato ? Esta retornando que não foi encontrado a lista de serviço. Fiz o teste com Postman retornou o mesmo erro.
Tem algum lugar no site dos correios que eu consigo ver minha lista de serviços ?

```
"msgs": [
        "CON-012: Os serviços não foram encontrados. Contrato: XXXXX, CNPJ: XXXXXX, cartão de postagem: XXX"
    ],
```

**Comment by tgoribas** [comment]
Solucionado aqui, descobri que o contrato dos correios estava bloqueado. Depois que foi liberado funcionou!

**Comment by palimpsestus** [comment]
@tgoribas por aqui aconteceu algo parecido também. E depois que eu tirei o novo token, deu tudo certo.

**Comment by felipersilva-agro** [comment]
Sim @palimpsestus também foi assim no meu caso, eu deixei para trabalhar no dia seguinte, gerei um novo token e  e passou a funcionar também.

**Comment by luccavallari** [comment]
Bom dia! Mesmo com a API nova, estou recebendo muita mensagem de "Nenhuma opção de entrega foi encontrada para ". Mesmo de clientes que já tiveram pedidos. Atualizei tudo agora cedo, mas mesmo assim permanece isto.

**Comment by frepoe** [comment]
Boa Tarde! Tenho o mesmo problema  "Nenhuma opção de entrega foi encontrada para..."
Será necessário ter contrato com o correio? Não tenho volume para isso...

**Comment by luccavallari** [comment]
> Boa Tarde! Tenho o mesmo problema "Nenhuma opção de entrega foi encontrada para..." Será necessário ter contrato com o correio? Não tenho volume para isso...

Sim, vc precisa de um contrato dos correios ativo para fazer funcionar.

Eu conseguir resolver meu problema após remover o plugin e reinstalar.
