### ISSUE TITLE
Alias de integração com o Bling

### ISSUE THREAD

**Issue by rafamonteiroo** [claudiosmweb/woocommerce-correios#256]
Olá, nessa ultima versão, notei que os alias de SEDEX ou PAC estão o mesmo: correios-cws , ai o Bling não consegue diferenciar a forma de envio

**Comment by claudiosanches** [comment]
@rafamonteiroo o Bling não fez a integração da forma correta, eles apenas verificam pelo `method_id` que é o ID da classe do método de entrega, eles chamam isso de ID logistico, porém não é. Eu mesmo escrevi a API REST do WooCommerce e posso afirmar isso. Eles precisavam usar o `instance_id` também para poder diferenciar, até mesmo porque se você usar os métodos do WooCommerce como "Taxa Fixa (Flat Rate)" para coisas como um motoboy em uma area de entrega, PAC de grana para uma area de entrega especifica por CEP e SEDEX com um preço fixo para outra área de entrega que você separou por CEP, pronto, no Bling ou só vai poder ser PAC ou Sedex, eles não são capazes de identificar a diferença porque a integração deles foi feita errada, o meu plugin agora apenas deixa isso mais evidente que eles deveriam desde o começo juntar o `method_id` com o `instance_id`, que assim fica o ID da classe de entrega + o ID do método de entrega dentro da sua área de entrega. Ainda mais como o WooCommerce tem áreas de entrega, o Bling deveria ter considerado isso desde o inicio, porém agora você pode entrar em contato com eles e explicar tudo isso que eu falei ai e eles não vão fazer nada, vai sobrar pra mim ter que colocar uma opção neste plugin para hackear o WooCommerce e causar bug tirando os métodos de entrega dentro das areas de entrega fora de sincronia com os pedidos e causando vários bugs futuros, só porque o Bling não fez a integração correta e se ficam recusando a fazer de forma certa. Isso que vocês pagam o Bling e pra usar este plugin é de graça...
