### ISSUE TITLE
Adicionar frete por tabela

### ISSUE THREAD

**Issue by sebosfato** [claudiosmweb/woocommerce-correios#257]
Seria legal adicionar uma opção de adicionar tabelas de frete por transportador…
para podermos adicionar opção de motoboy, DHL, UPS

Alguém tem o conhecimento como adicionar esta função?

**Comment by sebrax** [comment]
Vejo que sai muito do escopo desse plugin mas busca por Table Rate Shipping for WooCommerce na galeria de plugins que tem alguns lá com essa solução. Vale também usar um integrador tipo a Frenet que da pra adicionar várias transportadoras na versão paga.

**Comment by sebrax** [comment]
> Seria legal adicionar uma opção de adicionar tabelas de frete por transportador… para podermos adicionar opção de motoboy, DHL, UPS
> 
> Alguém tem o conhecimento como adicionar esta função?

Vejo que sai muito do escopo desse plugin mas busca por Table Rate Shipping for WooCommerce na galeria de plugins que tem alguns lá com essa solução. Vale também usar um integrador tipo a Frenet que da pra adicionar várias transportadoras na versão paga.

**Comment by sebosfato** [comment]
Muito obrigado pela dica vou buscar sim! 
Eu estou tentando desenvolver um plugin também mas sou bem tosco em programação, seria um plugin para permitir adicionar dhl e ups shippings grátis para o woocommerce… 

não é tão fácil quanto parece mas acho q a gente chega la… 

to fazendo isso pq os plugins que encontrei custam vários dólares mensais para poder funcionar e acho que nos brasileiros temos que exportar nossos produtos para nosso pais crescer, então quero tentar deixar bem simplão mesmo mas funcional e gratuito para todos poderem usar… 

Todos sabemos da importância de ser competitivo com preços e na hora de exportar é bom oferecer pelo menos umas 3 opções para o cliente poder escolher… as vezes a mais barata ou a mais rápida etc… 

criei um repósitorio para o projeto https://github.com/sebosfato/UPS-LIVE-RATES-WOOCOMMERCE-PLUGIN.git

ainda não ta funcionando na vdd mas em breve deve estar.. 

estou separando em alguns arquivos e penso em usar o carbon fields para fazer a parte interna… estava tentando com gpt mas é bem complexo… Na verdade é bem simples o conceito mas eu sinto que sou muito novato e me falta conhecimentos básicos…

**Comment by claudiosanches** [comment]
> Seria legal adicionar uma opção de adicionar tabelas de frete por transportador…
para podermos adicionar opção de motoboy, DHL, UPS

Você já pode fazer isso usando os métodos de entrega nativos do WooCommerce.
