### ISSUE TITLE
Nenhum frete disponível, às vezes

### ISSUE THREAD

**Issue by thiagolcks** [claudiosmweb/woocommerce-correios#26]
Nos últimos dias alguns clientes começaram a receber a mensagem: "Desculpe, o transporte está indisponível para Brasil.". Desativei o cache da taxa de entrega (Ferramentas / Modo depuração de entrega), e ao testar alguns CEPs eu recebo essa mensagem de erro eventualmente. No log eu encontrei a mensagem: "O Valor Declarado nao deve exceder R$ 10.000,00." ([log completo](https://gist.github.com/thiagolcks/a8d35f333e5a14a36278)).

O total do pedido é de R$398 e isso acontece algumas vezes. Se eu insistir no Calcular Frete do carrinho depois de algumas tentativas eu recebo as opções corretas de frete, e se insistir mais algumas vezes ele volta para a mensagem de erro.

Alguma ideia do que pode ser?

**Comment by claudiosmweb** [comment]
Esta tudo certo, os correios esta dando problemas nos ultimos tempos, tenta desativar a opção de declarar. Ela tem algumas horas que ao contrário de dar esse erro vai somar o valor e sair um frete bem mais caro que o normal.

**Comment by thiagolcks** [comment]
Obrigado pela resposta!

**Comment by jonathanafranio** [comment]
@claudiosanches  + uma vez, vlw.
