### ISSUE TITLE
Problemas com atualização 

### ISSUE THREAD

**Issue by LucasBarbosa88** [claudiosmweb/woocommerce-correios#264]
Estou usando a seguinte versão do wordpresss 4.8.7, e quando atualizei para a nova versão do plugin, meu sistema só fica no erro 500, não abre mais nada, o que poderia ser?

**Comment by claudiosanches** [comment]
Não consigo reproduzir esse problema. Veja o log de erros do servidor para ter certeza exatamente o que esta causando isso. Talvez você atualizou mais plugins e outro esta causando isso.
Fechando porque não tem nada indicando que é um problema neste plugin e não tem passos para reproduzir.
