### ISSUE TITLE
Valores de frete não é exibido!

### ISSUE THREAD

**Issue by itsdiegodutra** [claudiosmweb/woocommerce-correios#266]
Olá turma! Recém instalei o plugin, seguidos todas as orientações do vídeo de instalação, porém nem no carrinho e nem no checkout, os valores de fretes, PAC, Sedex, etc, são exibidos. Frete grátis, frete fixo, sim são exibidos. Quando atualizo a lista de serviços, tenho retorno positivo e a lista fica disponível para a configuração a cerca daquilo que preciso, mas sem aparecer para finalização.

**Comment by claudiosanches** [comment]
Olá. No caso não esta aparecendo porque deve ter algo ainda incorreto na sua configuração, se ativar o log do plugin vai mostrar exatamente o motivo dos Correios não retornar frete.
Fechando já que não é um problema neste plugin.
