### ISSUE TITLE
Mostrar resultado do cálculo

### ISSUE THREAD

**Issue by mruoppolo** [claudiosmweb/woocommerce-correios#28]
Olá, tudo bem?

Quando um calculo de frete é feito no meu site, após recarregar a página o site fica mostrando o topo, eu precisava que o site descesse até onde esta mostrando as opções de frete e os valores, também preciso colocar um aviso dentro da data de entrega dizendo o seguinte "Após o envio" para ficar mais ou menos assim: "Entrega em 6 dias úteis. Após o envio".

Como posso fazer??

Muito obrigado pela ajuda

**Comment by claudiosmweb** [comment]
Comportamento nativo do WooCommerce é recarregar e ficar até o topo, se quer mudar isso, mude no WooCommerce.
Para mudar os títulos dos métodos de entrega você pode fazer utilizando o filtro `woocommerce_correios_shipping_methods`.
