### ISSUE TITLE
Método de envio inválido

### ISSUE THREAD

**Issue by di3gof3rn4ndes** [claudiosmweb/woocommerce-correios#32]
Olá Cláudio, não é possível finalizar o pedido, aparece a mensagem de método de envio inválido.

06-23-2015 @ 17:40:16 - Weight and cubage of the order: Array
(
    [height] => 2
    [length] => 16
    [width] => 11
    [weight] => 10
)

06-23-2015 @ 17:40:16 - Requesting the Correios WebServices...
06-23-2015 @ 17:40:17 - Correios WebServices response [PAC]: SimpleXMLElement Object
(
    [Codigo] => 41106
    [Valor] => 0,00
    [PrazoEntrega] => 0
    [ValorSemAdicionais] => 0,00
    [ValorMaoPropria] => 0,00
    [ValorAvisoRecebimento] => 0,00
    [ValorValorDeclarado] => 0,00
    [EntregaDomiciliar] => S
    [EntregaSabado] => N
    [Erro] => 999
    [MsgErro] => CEP de origem inexistente, consulte o Busca CEP.
)

**Comment by claudiosmweb** [comment]
Ai o erro:

```CEP de origem inexistente, consulte o Busca CEP.```
