### ISSUE TITLE
Calculo de Cubagem e Peso Máximo Opcional

### ISSUE THREAD

**Issue by kaiuaki** [claudiosmweb/woocommerce-correios#33]
O plugin calcula o máximo de cubagem e peso do total de produtos comprados na loja.
Deveria existir uma opção de desativar isto ou adicionar pacotes automaticamente.

Veja bem, na minha loja cada produto tem 20kg e a embalagem é 20x50x50 cm.
O cliente comprando mais de 1 da um erro geral  e nem é mostrado o frete.

**Comment by claudiosmweb** [comment]
Sinta-se livre para enviar um Pull Request com essa opção.
