### ISSUE TITLE
Error accessing the Correios WebServices: Array

### ISSUE THREAD

**Issue by luizbueno** [claudiosmweb/woocommerce-correios#35]
Boa tarde;

Estou com problemas no calculo de frete utilizando o plugin do Woocomerce Correios.

Na tela de compra, quando o cep é digitado, está aparecendo a seguinte mensagem:

Não foi possível calcular o frete, por favor, tente adicionar o produto ao carrinho e prossiga para o pagamento para tentar ver o valor do frete.

Na tela do carrinho de compras e no checkout, está aparecendo a seguinte mensagem:

Não existe nenhum método de entrega disponível. Por favor, certifique-se de que o seu endereço esta correto ou entre em contato conosco caso você precise de ajuda.

Habilitei o log para ver como o plugin está comunicando com o webservice dos correios e o resultado foi:

```javascript

09-26-2015 @ 20:44:11 - Weight and cubage of the order: Array
(
    [height] => 9
    [length] => 16
    [width] => 18
    [weight] => 0
)

09-26-2015 @ 20:44:11 - Requesting the Correios WebServices...
09-26-2015 @ 20:44:12 - Error accessing the Correios WebServices: Array
(
    [headers] => Array
        (
        )

    [body] =>
    [response] => Array
        (
            [code] => 0
            [message] =>
        )

    [cookies] => Array
        (
        )

    [filename] =>
)

```
Já tentei desinstalar alguns plugins que eu não uso, e tentei reinstalar e instalar novamente o plugin Woocomerce Correios. Porem o erro ainda persiste.

Estou usando o WordPress 4.3.1, WooCommerce 2.4.7 e o Plugin WooCommerce Correios 2.3.0.

Vocês podem verificar o problema em: http://loja.evilmatchers.com/produto/camisa-evil-matchers-preta/

Gostaria de saber se vocês já passaram por este problema, e se conseguiram alguma solução.

Obrigado!

**Comment by claudiosmweb** [comment]
Isso definitivamente não é um problema com este plugin.
A resposta esta vazia, ou o site dos Correios caiu ou o seu site esta totalmente incapaz de fazer a comunicação com o site dos Correios.

Tenta instalar novamente cURL no seu servidor.
