### ISSUE TITLE
alguns CEPs não calcula frete

### ISSUE THREAD

**Issue by kaiuaki** [claudiosmweb/woocommerce-correios#36]
Por exemplo: 08420-000

Na cissa carrega.
No kabum carrega.
Nos correios carrega.
Neste plugin não carrega este cep.

O que será?

**Comment by kaiuaki** [comment]
No simulador não carrega, mas no carrinho carrega. Estou efetuando novos testes.

**Comment by claudiosmweb** [comment]
Porque não envia dados corretos.
Provavelmente não tem peso ou dimensões no produto.

**Comment by kaiuaki** [comment]
Não, eu testei 39 ceps de 5 estados, ate acre, bahia, pernambuco, são paulo, rio de janeiro etc.
Numa instalação limpa, produto 1 kg e as dimensões padrão mínimas do correios.

**Comment by kaiuaki** [comment]
O cep pelo que percebi está numa área de restrição dos Correios.
