### ISSUE TITLE
CEPs não calcula frete [simulador-summary] (por favor checar amtes de fechar, simulei o erro em vários sites)

### ISSUE THREAD

**Issue by kaiuaki** [claudiosmweb/woocommerce-correios#37]
Claudio se o problema fosse atributos de peso ou dimensoes invalidas concorda comigo que nenhum cep deveria simular?

Por que você trancou o outro post sem nem me da a chance de replica? Segunda vez isso.. Poxa sempre ajudo com doaçoes, todo mês..

Bom vamos la.

Criei um produto teste, 1kg, dimensão: 20cm 20cm 20cm, valor declarado R$ 6.000,00.
Depois criei o memo produto com valor de R$ 20,00

Mesmo problema.

Todos os ceps que eu testei funcionaram menos este. O fato de ser restrito te alguma coisa a ver?

Obs: O erro só ocorre no simulador.

**Comment by kaiuaki** [comment]
Comecei a testar em todas as lojas que conheço que usam o seu plugin, pasmem. MESMO ERRO.

CEP: 08420-000
Por favor verifiquem antes de fechar um issue.

Instalação limpa, mesmo erro no simulador.
Sites que encontrei pela net, deu o memso erro.

**Comment by claudiosmweb** [comment]
Não tenho nada para verificar, se não funciona, é porque não funciona nos Correios.
Não é problema com o plugin!

**Comment by claudiosmweb** [comment]
Alias, plugin é open source, minha ajuda aqui é gratuita.
Leia a licença GPLv2:
https://creativecommons.org/licenses/GPL/2.0/legalcode.pt

Principalmente esta parte:

>EXCLUSÃO DE GARANTIA
>
> COMO O PROGRAMA É LICENCIADO SEM CUSTO, NÃO HÁ NENHUMA GARANTIA PARA O PROGRAMA, NO LIMITE PERMITIDO PELA LEI APLICÁVEL. EXCETO QUANDO DE OUTRA FORMA ESTABELECIDO POR ESCRITO, OS TITULARES DOS DIREITOS AUTORAIS E/OU OUTRAS PARTES, FORNECEM O PROGRAMA "NO ESTADO EM QUE SE ENCONTRA", SEM NENHUMA GARANTIA DE QUALQUER TIPO, TANTO EXPRESSA COMO IMPLÍCITA, INCLUINDO, DENTRE OUTRAS, AS GARANTIAS IMPLÍCITAS DE COMERCIABILIDADE E ADEQUAÇÃO A UMA FINALIDADE ESPECÍFICA. O RISCO INTEGRAL QUANTO À QUALIDADE E DESEMPENHO DO PROGRAMA É ASSUMIDO POR VOCÊ. CASO O PROGRAMA CONTENHA DEFEITOS, VOCÊ ARCARÁ COM OS CUSTOS DE TODOS OS SERVIÇOS, REPAROS OU CORREÇÕES NECESSÁRIAS.
>EM NENHUMA CIRCUNSTÂNCIA, A MENOS QUE EXIGIDO PELA LEI APLICÁVEL OU ACORDADO POR ESCRITO, QUALQUER TITULAR DE DIREITOS AUTORAIS OU QUALQUER OUTRA PARTE QUE POSSA MODIFICAR E/OU REDISTRIBUIR O PROGRAMA, CONFORME PERMITIDO ACIMA, SERÁ RESPONSÁVEL PARA COM VOCÊ POR DANOS, INCLUINDO ENTRE OUTROS, QUAISQUER DANOS GERAIS, ESPECIAIS, FORTUITOS OU EMERGENTES, ADVINDOS DO USO OU IMPOSSIBILIDADE DE USO DO PROGRAMA (INCLUINDO, ENTRE OUTROS, PERDAS DE DADOS OU DADOS SENDO GERADOS DE FORMA IMPRECISA, PERDAS SOFRIDAS POR VOCÊ OU TERCEIROS OU A IMPOSSIBILIDADE DO PROGRAMA DE OPERAR COM QUAISQUER OUTROS PROGRAMAS), MESMO QUE ESSE TITULAR, OU OUTRA PARTE, TENHA SIDO ALERTADA SOBRE A POSSIBILIDADE DE OCORRÊNCIA DESSES DANOS.

Em outras palavras, você não tem direito de exigir absolutamente nada!

**Comment by claudiosmweb** [comment]
E não se preocupe, vou retirar o simulador da página do produto na próxima versão do plugin.
Então de qualquer forma seu problema vai ser resolvido.

**Comment by jonasrafael** [comment]
Por causa desse caboclo que o simulador saiu? :(
