### ISSUE TITLE
CEPs erro no simulador (3ª tentativa de colocar o erro aqui)

### ISSUE THREAD

**Issue by kaiuaki** [claudiosmweb/woocommerce-correios#38]
Prezado Claudio, não, o erro não é nos Correios.

As lojas que fucnionam o cep e não usam o seu plugin usam o webservice dos Correios. Na verdade só o teu plugin da erro nestes ceps. Isso não é algo ruim man. Não estou aqui para exigir, criticar. Estou aqui na condição de humildemente expor esta falha, conversar sobre ela, etc. Nosso programador não identificou ela.

Por obséquio, quando e se tiver tempo, veja isso.

Eu sei que sou livre para contratar um programador.
Eu sei que o código é livre.
Eu sei que você não tem obrigação nenhuma de fazer nada.

Não precisa tirar este recurso do próximo release. Isso não seria legal com os que usam este recurso, com os que te apoiam.

Têm muita gente no sense, não sou um deles.

Estou na maior boa vontade aqui como sempre fui contigo.
Por favor reconsidere.

**Comment by claudiosmweb** [comment]
Estou removendo o recurso do próximo release.
