### ISSUE TITLE
Peso adicional ou peso da embalagem padrão

### ISSUE THREAD

**Issue by TiagoValdo** [claudiosmweb/woocommerce-correios#40]
Olá Claudio, beleza?

Estou utilizando seu plugin num site de e-commerce que estou desenvolvendo para mim mesmo e gostaria de uma ajuda com a questão do peso.

Eu vendo produtos pequenos que pesam entre 10 e 30g, não muito mais que isso.
A embalagem que eu uso para enviar, mais as outras coisas que vão dentro, pesa +/- 90 a 100g.

Assim, se eu configurar cada produto individualmente para 100g (10 do produto + 90 da embalagem), e um cliente comprar 10 produtos, o calculo do peso chega em 1Kg, quando na verdade, daria uns 200g.

Seria possível ter um campo para colocar um peso adicional para calcular o envio? Ou talvez um peso da embalagem padrão? Funcionaria mais ou menos igual o valor de manuseio.

**Comment by claudiosmweb** [comment]
Pode usar o filtro `woocommerce_correios_shipping_args` para somar mais peso.

**Comment by TiagoValdo** [comment]
Obrigado Cláudio! Valeu pela dica. Vou fazer aqui.
