### ISSUE TITLE
Custom template for simulator-data block

### ISSUE THREAD

**Issue by dbasilioesp** [claudiosmweb/woocommerce-correios#41]
Na página Single Product, seria interessante o desenvolvedor usuário do plugin ter capacidade de alterar o formato do template que o simulador do frete responde por ajax.
Hoje o formato é editado pelo script assets/js/simulator.js, apenas possibilitando a alteração do estilo.

In Single Product, should be good the user-developer of plugin be capable to format the simulator response of ajax.
Now, the format is edited by the script assets/js/simulator.js, just letting the developer change the style of the code block.

```js
success: function ( data ) {
	button.removeClass( 'loading' );
	button.removeAttr( 'disabled' );

	if ( 0 < data.error.length ) {
		content.prepend( '<p class="error">' + data.error + '</p>' );
	} else if ( 0 < data.rates.length ) {
		var shipping = '<ul id="shipping-rates">';

		$.each( data.rates, function( key, value ) {
			shipping += '<li>' + value.label + ': ' + value.cost + '</li>';
		});

		shipping += '</ul>';

		content.prepend( shipping );
	} else {
		content.prepend( '<p class="error">' + woocommerce_correios_simulator.error_message + '</p>' );
	}
},
```

**Comment by claudiosmweb** [comment]
Não se preocupe, o simulador da página do produto vai ser removido na próxima versão do plugin.
