### ISSUE TITLE
Integração com API

### ISSUE THREAD

**Issue by marciogm** [claudiosmweb/woocommerce-correios#44]
Olá,
Tenho uma duvida, usando a API REST do woocommerce, quando faço a requisição /orders/<id>.
Existe alguma maneira de pegar as informações do código de rastreio? ou apenas o código de rastreio para o pedido.
As informações que me retornam, não contem as informações do rastreio.

Obrigado

**Comment by marciogm** [comment]
Falta de pesquisa, "orders/<id>?filter[meta]=true".

**Comment by claudiosmweb** [comment]
Esse campo não faz parte da API, precisa ser adicionado.
