### ISSUE TITLE
Adicionar função para buscar endereço baseado no CEP

### ISSUE THREAD

**Issue by claudiosmweb** [claudiosmweb/woocommerce-correios#45]
Para facilitar a vida de quem precisa trabalhar com endereços baseados em CEP.

**Comment by danilowm** [comment]
no carrinho quando tem o Calcular frete fazer algum botão para "descobrir o cep" baseado no endereço?
se for isso, vou tentar te ajudar nessa

**Comment by claudiosmweb** [comment]
@danilowm sim.

**Comment by claudiosmweb** [comment]
Na verdade escrevi errado, é uma função para ajudar a buscar o endereço baseado no CEP, como já é feito pelo carrinho, mas permitir usar isso em qualquer lugar.
