### ISSUE TITLE
Cálculo de frete na página do produto

### ISSUE THREAD

**Issue by thiagopeixoto16** [claudiosmweb/woocommerce-correios#46]
Esta função foi migrada para algum outro plugin?
Sabe como faço para ter cálculo de frete na página do produto?
Obrigado!

**Comment by lenivene** [comment]
O seu tá configurado?

_Clique abaixo e assista o vídeo do @claudiosmweb ensinando a configurar_

[![Configurando o Woocommerce Correios 3.0](http://img.youtube.com/vi/IWjLAy9i--I/0.jpg)](http://www.youtube.com/watch?v=IWjLAy9i--I)

**Comment by thiagopeixoto16** [comment]
Está sim @lenivene, mas sumiu da página do produto, o cálculo de frete (estimativa).

**Comment by lenivene** [comment]
@thiagopeixoto16 está se referindo ao simulador? se sim, foi removido na versão 3.0.0

**Comment by claudiosmweb** [comment]
Não tem mais isso na página do produto, não fazia parte do escopo do plugin e coloquei para ajudar os usuários, mas tive apenas dor de cabeça com isso e nunca ninguém entendeu que era para ajudar.
Também iria fazer um plugin especialmente para isso e que iria suportar qualquer método de entrega, mas novamente, por causa de alguns usuários, que não vou fazer isso.

**Comment by Luc45** [comment]
@claudiosanches sabe dizer em que versão foi removido, por gentileza?
