### ISSUE TITLE
Integração com Sigep

### ISSUE THREAD

**Issue by amedtler** [claudiosmweb/woocommerce-correios#48]
Esse plugin tem integração com sigep web?

**Comment by brunocardon** [comment]
Creio que não, também gostaria hehehe!
Mas dentro das configurações do método de entrega "Correios", tem a opção "Serviço corporativo" que ao escolher "Corporativo" aparecem duas novas opções:

-Código Administrativo;
-Senha Administrativa.

Mas não sei para que servem...

**Comment by lucasfaria** [comment]
Esses campos funcionam quando você tem algum contrato com os Correios. O frete fica mais barato nesse caso.

**Comment by claudiosmweb** [comment]
Se for integração com a SIGEP WEB para criar etiquetas, então não tem, mas fico aguardando ansiosamente pelo seu Pull Request ajudando implementar isso.

**Comment by larodiel** [comment]
Pessoal, algumas coisas para quem quiser dar uma olhada nisso e quem sabe implementar no plugin.

https://github.com/stavarengo/php-sigep ( Repositório com algumas classes e métodos que podem ajudar )
http://www.corporativo.correios.com.br/encomendas/sigepweb/doc/Manual_de_Implementacao_do_Web_Service_SIGEP_WEB.pdf
Documentação da API, nela contém a URL para o ambiente de DEV dos correios e fornece também um usuário para que se possa testar a integração.

**Comment by luisetmelo** [comment]
Será que já tem alguma novidade sobre a integração com o SIGEP para geração de etiquetas e atualização dos status?

@claudiosanches obrigado pelo plugin!
