### ISSUE TITLE
Dúvida quanto ao filtro "woocommerce_correios_email_tracking_message"

### ISSUE THREAD

**Issue by brunocardon** [claudiosmweb/woocommerce-correios#49]
Boa Noite!

Estou desenvolvendo um plugin para WooCommerce e como também estou utilizando o WooCommerce Correios em meu site, aproveitei e dei uma olhada no código para buscar referências e aprender um pouco mais.

Neste plugin que estou desenvolvendo, assim como o WooCommerce Correios, estou criando um novo template para envio de notificações por e-mail. Estava estudando o arquivo [https://github.com/claudiosmweb/woocommerce-correios/blob/master/includes/emails/class-wc-correios-tracking-email.php](url), e me deparei nas linhas 117 e 134 o seguinte código:

117
`return apply_filters( 'woocommerce_correios_email_tracking_message', $this->format_string( $this->tracking_message ), $this->object );`

134
`return apply_filters( 'woocommerce_correios_email_tracking_core_url', $url, $tracking_code, $this->object );`

Procurei por tudo, pesquisei como funciona, mas não consegui descobrir como esse filtro funciona, aonde foi declarado, etc. Simplesmente não consegui intender como ele funciona...

Ao declararmos uma classe `extends WC_Email` é criado algum filter dinamicamente?

Desde já agradeço!
E agradeço mais ainda pelos ótimos plugins!

**Comment by claudiosmweb** [comment]
> Procurei por tudo, pesquisei como funciona, mas não consegui descobrir como esse filtro funciona, aonde foi declarado, etc. Simplesmente não consegui intender como ele funciona...

Esta sendo declarado exatamente onde você mostrou.

Seria bom ler isso para entender como filtros funcionam: https://codex.wordpress.org/Plugin_API/Filter_Reference

> Ao declararmos uma classe `extends WC_Email` é criado algum filter dinamicamente?

Nenhum filtro é criado dinamicamente, mas pode usar os filtros que já existem em `WC_Email`
