### ISSUE TITLE
Trocar texto entrega

### ISSUE THREAD

**Issue by amedtler** [claudiosmweb/woocommerce-correios#50]
Olá! Gostaria de trocar o texto da entrega. 
Ex: PAC (Entrega em 5 dias úteis):
Para: 
PAC (Entrega estimada em 5 dias úteis):

Como posso fazer isso?

**Comment by claudiosmweb** [comment]
Pode usar o filtro `woocommerce_correios_correios-pac_rate`.

Por exemplo:

```php
add_filter( 'woocommerce_correios_correios-pac_rate', function( $data ) {
    $data['label'] = str_replace( 'Entrega em', 'Entrega estimada em', $data['label'] );

    return $data;
});
```

**Comment by amedtler** [comment]
Obrigado pelo retorno. Coloquei esse código no arquivo functions.php, porém não deu certo. Devo fazer diferente?

**Comment by claudiosmweb** [comment]
Como eu falei, esse código ai é um exemplo.

**Comment by amedtler** [comment]
Ok. Obrigado. Consegui resolver de outra forma.
