### ISSUE TITLE
Adicionando a opção de Reenviar Código de Rastreio.

### ISSUE THREAD

**Issue by brunocardon** [claudiosmweb/woocommerce-correios#52]
Boa Noite!

Estou utilizando o WooCommerce Correios 2.3.0, mesmo lendo os updates para o 3.0.6 não encontrei a adição que vou sugerir.

Nos detalhes dos pedidos no painel do Wordpress, temos a opção de reenviar algumas notificações por e-mail, Novo Pedido, Pedido Cancelado, Processando Pedido, etc, gostaria de poder reenviar o código de rastreio para o cliente, sem ter que descadastrar o código e cadastrar novamente, pois isso por mais simples que pareça ser, é chato de pedir o administrador do site fazer.

Pois bem, como não sei direito como fazer o "Pull request" aqui do github, vou sugerir por aqui:

No arquivo `includes/emails/class-wc-email-correios-tracking.php` na function `function __construct()` adicionar o seguinte filter:
```
 add_filter( 'woocommerce_resend_order_emails_available', array($this, 'Correios_Tracking_resend_order_emails_available'), 10, 1 ); 
```

Posteriormente adicionar a seguinte function:

```
public function Correios_Tracking_resend_order_emails_available($array){

$array[] = 'correios_tracking';

return $array;
}
```

Isto vai adicionar a opção de reenviar o código de rastreio na meta_box "Ações do Pedido" nos detalhes do pedido.

**Comment by claudiosmweb** [comment]
@brunocardon obrigado pela sugestão.
