### ISSUE TITLE
Exibição de frete gratis para trechos indisponiveis

### ISSUE THREAD

**Issue by rafa-acioly** [claudiosmweb/woocommerce-correios#54]
Alguns clientes estão recebendo a opção de frete gratuito usando a modalidade de `sedex 10` quando  o correio retorna a mensagem de erro "Serviço indisponível para o trecho informado." (código do erro 008)

Registro do Log;

```
08-31-2016 @ 10:41:27 - Correios WebServices response [SEDEX 10]: SimpleXMLElemento Object
(
   [Codigo] => 40215
   [Valor] => 0,00
   [PrazoEntrega] => 0
   [ValorSemAdicionais] => 0,00
   [ValorMaoPropria] => 0,00
   [ValorAvisoRecebimento] => 0,00
   [ValorValorDeclarado] => 0,00
   [EntregaDomiciliar] => SimpleXMLElement Object
     (
     )

   [EntregaSabado] => SimpleXMLElement Object
     (
      )

   [Erro] => 008
   [MsgErro] => Serviço indisponível para o trecho informado.
)
```

Localizei no arquivo [wc-correios-function.php](https://github.com/claudiosmweb/woocommerce-correios/blob/master/includes/wc-correios-functions.php#L102) a função que pega os erros vindos do correio e notei que não consta o erro `'008'`, incluir esta opção resolveria o problema ou é algo a mais que deve ser feito?

Notei também a função que verifica se o produto é gratuito;

```
protected static function get_price( $value ) {
		if ( 0 == $value ) {
			return __( '(Free)', 'woocommerce-correios' );
		}

		return sanitize_text_field( wc_price( $value ) );
	}
```

No meu caso o valor é 0 sim pois o correio retornou um erro, como eu poderia fazer para validar se existe um erro também?

> Versão do Wc: 2.5.5
> Versão do Wp: 4.5

**Comment by claudiosmweb** [comment]
Bom isso deve corrigir esse problema agora.
Não gosta na função, porque apenas os erros permitidos estão fazendo parte dela.

**Comment by claudiosmweb** [comment]
E sem preço nunca deve passar por causa https://github.com/claudiosmweb/woocommerce-correios/blob/master/includes/abstracts/abstract-wc-correios-shipping.php#L423-L426
