### ISSUE TITLE
Conclusão automática após a entrega

### ISSUE THREAD

**Issue by brunokruger** [claudiosmweb/woocommerce-correios#59]
Olá Claudio, tudo bem?

Saberia me dizer se é possível criar uma forma dos pedidos que estão com o código dos correios mudarem o status para concluído quando o status dos correios também estiver concluído? 

Obrigado.

**Comment by claudiosmweb** [comment]
Pode criar um cron no servidor para verificar eles e atualizar sim.
Boa sorte.
