### ISSUE TITLE
Cálculo de frete Correios Internacional

### ISSUE THREAD

**Issue by adrianovarlotta** [claudiosmweb/woocommerce-correios#6]
Tem algum jeito de funcionar o frete para exterior ou só nacional mesmo?
Tem alguma outra forma de fazer funcionar frete para o exterior?

Obrigado

**Comment by elsondinardo** [comment]
Alguém poderia fazer fazer um módulo gratuito para Magento de cálculo internacional. Seria lindo, um sonho.

**Comment by claudiosmweb** [comment]
@elsondinardo se quiser use WooCommerce, não vamos fazer nada para Magento.

**Comment by acthomazelli** [comment]
Vejam se essa informação acrescenta algo

http://www.correios.com.br/para-voce/correios-de-a-a-z/pdf/calculador-remoto-de-precos-e-prazos/manual-de-implementacao-do-calculo-remoto-de-precos-e-prazos

**Comment by claudiosmweb** [comment]
@acthomazelli isso que você passou é a API que já usamos e que funciona apenas para o Brasil.

**Comment by acthomazelli** [comment]
Ihh caramba, enviei o link errado.
Bem, como ainda não descobri solução melhor, comprei o Table Rate Shipping.
É caro, custa  US$199,00, mas pra mim que tinha pressa na solução, resolveu.
http://www.woothemes.com/products/table-rate-shipping/

**Comment by romuloctba** [comment]
Não sei se seria uma boa juntar à este plugin essa consulta internacional.

Primeiro pq nos correios padronização de C é R. Saca só a diferença dos parâmetros.
Pensei assim 'rá, demorou, vou kibar o claudio e alterar os nomes dos métodos e a url do webservice'. Mas não, os correios fizeram questão de fazer algo totalmente diferente do cálculo de frete normal.

Aí logo no init() do woocommerce-correios temos o `$avaliability':
``` 
$this->availability       = 'specific';
$this->countries          = array( 'BR' );
```
Pra fazer o internacional teria de ser o oposto.
Mas acho que não dá pra alterar isso, visto que tá no __construct né? tb nao sei

Bom , d qqh forma, oq eu estou fazendo agora é usar o woocommerce-correios como 'guia' pra criar um shipping method com base [neste tuto](http://docs.woothemes.com/document/shipping-method-api/) bonitinho do Woo.

Tá até que dando certo, embora eu tenha travado aqui no `calculate_shipping( $package ) ` pq não queria copiar a classe `WC_Correios_Package` toda... Mas acho no fim vai ser isso, afinal ela que soma os tamanhos do produto pra poder fazer o rate com per_order né?

Bom, malz aí o texto e sei q nao tem mto a ver com este plugin, mas a thread veio a calhar.

De qualquer forma, as informações do link são ótimas:
```
// Documento: http://www.correios.com.br/para-sua-empresa/servicos-para-o-seu-contrato/precos-e-prazos/calculador-remoto-de-precos-e-prazos/pdf/EFI_Manual_Implementacao_Calculo_Remoto_de_Precos_e_prazos.pdf
//
// Webservice url: http://www2.correios.com.br/sistemas/efi/bb/Consulta.cfm?
// - parâmetros:
//tipoConsulta=Geral
//&PAIS=US
//&ALTURA=15
//&LOCALIDADE= C de Capital ou I de Interior
//&PROFUNDIDADE=15
//&LARGURA=15
//&ESPECIF=110 tipo de serviço... 110 é ems, ve no documento as outras
//&PESO=1000
//&UFORIGEM=CE
//&RESET=TRUE
```

**Comment by claudiosmweb** [comment]
@romuloctba da para adicionar opções para alterar isso dai, entretanto coloquei desta forma, já que são necessárias estas opções e o plugin funciona só no Brasil.
De qualquer forma, estou considerando também em ter um segundo plugin para isso.
Talvez até dividir este plugin em outros, já que esta começando ficar gigante e tem outros métodos para serem incorporados.

**Comment by romuloctba** [comment]
Eu achei maior zoeira esse WS do internacional em relação ao do nacional, deveriam ao menos ter seguido um padrão...
Bom, assim q tiver funcionando bonitinho a minha integração aqui boto na roda pra galera decidir oq fazer ^^

**Comment by claudiosmweb** [comment]
Podemos criar um repo novo para trabalhar nisso.
Estou arrumando uns outros plugins por enquanto, tenho um plugin de descontos dando problema para usuários na Alemanha, além de umas integrações com o MercadoPago. Depois disso vou conseguir ter tempo para colocar as coisas aqui em ordem.

**Comment by romuloctba** [comment]
eu to me batendo com o $package do `calculate_shipping( $package ) ` pq nao consigo dar print_r pra ver oq tem no obj hahaha :( acho q vou ter q kibar sua classe tb

**Comment by romuloctba** [comment]
@claudiosmweb  ei o meu tá funcional aqui :)  ao final do dia eu posto em novo repo o/
Mas aviso desde já que não tá nem perto desse aqui :P

**Comment by romuloctba** [comment]
@claudiosmweb  e a quem interessar: tá na roda https://github.com/RcDevLabs/WooCommerce-Correios-International

Gostaria de saber se o @claudiosmweb acha adequado que este plugin (este aqui, o WooCommerce Correios) tenha a opção dos Correios International. 

Caso ache que sim, posso fazer uns PRs, ou qualquer coisa, o código está a disposição para quem quiser fazê-lo, pois não sei se é realmente interessante ter um plugin só para internacional shipping.. 
Ainda mais que metade das classes existentes neste aqui podem ser bastante úteis para o internacional, então teria que copiar metade do plugin neh, principalmente pra rastreio e tal...

O código tá bem cru e zoado, mas como estou sem tempo de trabalhar nele no momento, estou botando na roda pra quem quiser brincar, ou precisar disso com urgência, já ter meio caminho andado

Enfim, é isso, abraços , nao xingue (muito) meu código Cláudio, por favor.

**Comment by brazabr** [comment]
@romuloctba Acho interessante destacar alguns detalhes:
* O webservice que você está utilizando é para o produto Exporta Fácil, isso precisa ficar claro.
* Você fixou o código de especificação em 110 (Expressa via EMS), quando existem pelo menos 3 opções. Existem ainda o Sedex Mundi e a Encomenda Econômica (prazo grande, mais barata).

Esse documento, embora esteja com o endpoint inválido, contém os possíveis parâmetros de entrada e saída. 
http://blog.correios.com.br/comercioeletronico/wp-content/uploads/2012/03/Consulta_ExportaFacil.pdf

**Comment by brazabr** [comment]
Encontrei uma documentação mais atual:
http://www.correios.com.br/para-sua-empresa/servicos-para-o-seu-contrato/precos-e-prazos/calculador-remoto-de-precos-e-prazos/pdf/EFI_Manual_Implementacao_Calculo_Remoto_de_Precos_e_prazos.pdf

**Comment by romuloctba** [comment]
@brazabr sim, essa questão dos diferentes serviços está nos [Milestones](https://github.com/RcDevLabs/WooCommerce-Correios-International/milestones). Bem lembrado referente ao exporta fácil.

Acho importante qualquer observação a respeito do international seja feita no [Repositório correto](https://github.com/RcDevLabs/WooCommerce-Correios-International), pra não enchermos essas issues aqui

**Comment by brazabr** [comment]
@romuloctba Faz sentido. Leve por favor esses documentos e anexe ao seu repositório e se der eu colaboro com alguns PR.

**Comment by claudiosmweb** [comment]
Vai fazer parte da versão 3.0.0.

**Comment by romuloctba** [comment]
#topzeira
Em 12/06/2016 01:08, "Claudio Sanches" <notifications@github.com> escreveu:
