### ISSUE TITLE
Regras do Envio para Pacotes Muito Grandes (Produto ou Produtos)

### ISSUE THREAD

**Issue by jonasrafael** [claudiosmweb/woocommerce-correios#60]
Quando adicionar produtos que sozinhos ou somados tem o cm máximo (2000) dos correios, ou o peso máximo 30 kg. É fornecido outra forma de pagamento (ex: transportadora) ou valor fixo, é possível.

**Comment by jonasrafael** [comment]
Já achei aqui, advanced-free-shipping resolve meu problema. Mas seria legal que ao ultrapassar isso, mostrar uma mensagem dizendo que os correios não é capaz de enviar o pedido. Também percebi que se trata do erro mais comum, não só para os usuários do front, quanto para os gestores do back, que muitas vezes não assimilam o erro com o número errado do peso do produto.

**Comment by claudiosmweb** [comment]
O erro é salvo no log e da para gerenciar isso.
Não é o tipo de erro que pode ser mostrado na frente do site, além que dizer que não tem métodos de entregas disponíveis é bem melhor do que dizer que o cliente esta comprando algo muito grande e que os Correios não consegue entregar :P
