### ISSUE TITLE
Cep de Origem - Variável

### ISSUE THREAD

**Issue by jonasrafael** [claudiosmweb/woocommerce-correios#61]
Percebi que o CEP de origem é fixo, seria legal se ele tivesse uma opção de integração com o produto do Woo, wcpv_product_vendors.

Dessa forma, caso você tenha vendedores definidos para um produto. O cep de cálculo vai ser fornecida em um campo no Woocommerce Product Vendors.

**Comment by claudiosmweb** [comment]
Vai ser resolvido com o #55, assim vai dar para configurar cada método baseado em classes de entregas de produtos.

Sobre o product vendors da para criar integração com isso e usar o filtro `woocommerce_correios_origin_postcode` que assim pode manipular o CEP de origem como preferir no carrinho.

**Comment by jonasrafael** [comment]
Massa, eu vou tentar passar o cep na variável woocommerce_correios_origin_postcode. Se rolar eu posto ai na sequência.

**Comment by miguelurtado** [comment]
Olá @jonasrafael conseguiu passar o CEP na variável?

**Comment by sendylago** [comment]
Olá @jonasrafael e @miguelurtado conseguiram algo?

**Comment by miguelurtado** [comment]
Olá @sendylago a partir da versão 3.2.0 você pode usar as classes de entrega para isso - https://github.com/claudiosanches/woocommerce-correios#320---20170307

**Comment by jubbiana** [comment]
Olá!
Quando configuro um método de entrega dos Correios no meu site, não aparece o campo CEP de origem. Vocês podem me ajudar?

**Comment by claudiosanches** [comment]
@jubbiana calculo de frete de Impresso normal e registro módico não necessita de CEP, tudo é feito pelo peso dos produtos, no site dos Correios tem instruções de como calcular isso.

**Comment by webmastertesco** [comment]
Pessoal, coloquei uma interação em #9. Demora para responderem????? Obrigado.
