### ISSUE TITLE
Se não calcular o frete na página do carrinho depois não funciona

### ISSUE THREAD

**Issue by camilohollanda** [claudiosmweb/woocommerce-correios#8]
Aqui está acontecendo o seguinte, se não calcular o frete na página do carrinho depois não funciona na página de pagamento.
Estou usando a versão atual, baixado do github.
Tentei fazer um rápido debug aqui e percebi que o que é enviado para o servidor é o postcode no checkout, mas só funciona quando é enviado o s_postcode no carrinho.
Estou tentando debugar aqui, se conseguir algo eu "forko e pullo". :-)

**Comment by viniciusgrando** [comment]
@prem-prakash Desculpe o delay mas você consegui achar alguma solução para isso? no meu tema também acontece. apenas no Mobile ele não executa a ação do JS ai so interpreta o <a href="#"> Jogando para o topo da página.

**Comment by claudiosanches** [comment]
@viniciusgrando como eu falei, não é relacionado com este plugin. Se precisa de ajuda com isso abra um tópico em https://br.wordpress.org/support/forum/plugins-e-codigos/
