### ISSUE TITLE
Suporte à Classes de Entrega

### ISSUE THREAD

**Issue by 2aces** [claudiosmweb/woocommerce-correios#9]
Muitas vezes, numa loja temos produtos que podem ser diretamente enviados pelo correio, mas também alguns produtos que requerem cuidados especiais de manuseio ou  embalagens especiais por serem frágeis. 

Nestes casos, o ideal é que possa ser criada uma classe de entrega que incluísse este custo adicional em produtos esepcíficos para envio por correios também.

**Comment by claudiosmweb** [comment]
Não parece ter mais utilidade para isso na versão 3.0.0 e com as áreas de entrega do WooCommerce.
